### ISSUE TITLE
Unable to use in console

### ISSUE THREAD

**Issue by wasif-saeed-confiz** [wpeterson/emoji#37]
Hi i am trying to use this gem functionality on rails console. I tried to require 'emoji' but get following exception.

```
LoadError: cannot load such file -- emoji
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from (irb):2
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /home/wasifsaeed/Projects/edu_boss/bin/rails:9:in `<top (required)>'
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `block in load'
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/wasifsaeed/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

```

**Comment by steveklabnik** [comment]
1. is it in your gemfile?
2. did you `bundle exec rails c`?

**Comment by wasif-saeed-confiz** [comment]
@steveklabnik No i installed it using gem install command. I ran console using only rails c. But one thing more i noticed that some of my gem in gemfile in dependend on gemoji and i think both have same class Emoji. Is this also a reason?

**Comment by steveklabnik** [comment]
> No i installed it using gem install command.

If you dont' have it in your `Gemfile`, then rails won't know about it, and won't load it.

> i noticed that some of my gem in gemfile in dependend on gemoji and i think both have same class Emoji. Is this also a reason?

This may or may not cause a problem, it depends

**Comment by wasif-saeed-confiz** [comment]
Thanks @steveklabnik for the help :+1: :+1:
